#!/bin/bash

echo "🚀 Production User Creation Script"
echo "================================="
echo ""
echo "This script will help you create a user in the production database."
echo ""
echo "⚠️  IMPORTANT: You need to run this on the production server!"
echo ""
echo "Option 1: Using Railway CLI"
echo "--------------------------"
echo "railway run npx tsx create-test-user.js"
echo ""
echo "Option 2: Using Railway Shell"
echo "-----------------------------"
echo "1. Open Railway dashboard"
echo "2. Go to your federated-memory service"
echo "3. Click 'Connect' -> 'Railway Shell'"
echo "4. Run: npx tsx create-test-user.js"
echo ""
echo "Option 3: Direct Database Connection"
echo "-----------------------------------"
echo "1. Get your production DATABASE_URL from Railway"
echo "2. Run locally with production database:"
echo "   DATABASE_URL='your-production-database-url' node create-test-user.js"
echo ""
echo "The script will create a user with:"
echo "- Email: keithrivas@gmail.com"
echo "- Password: 70%qe6izpQ&e17Fg1IHQ"
echo "- Verified: true"
echo ""
echo "After creating the user, you should be able to log in!"