[phases.setup]
nixPkgs = ["...", "nodejs_20", "openssl"]
aptPkgs = ["libssl-dev", "ca-certificates"]

[phases.install]
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"